apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo-namespace
spec:
  selector:
    app: demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
