apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo-namespace  # Add namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: elenaprogramer/demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres-service:5432/dians-users  # Use the service name here
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: dians