apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Access mode for the volume
  resources:
    requests:
      storage: 10Gi  # Storage size required for PostgreSQL data
